name = "VerifiedSabr"
version = "0.1.2"
keywords = ["math"]
defaultTargets = ["VerifiedSabr", "VerifiedSabrTests"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "VerifiedSabr"

[[lean_lib]]
name = "VerifiedSabrTests"
globs = ["VerifiedSabr.Tests.+"]

[[lean_exe]]
name = "sabrsearch"
root = "Main"
